name: qr_master
description: A modern QR code scanner and generator.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.5
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qr.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/qr.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/qr.png"
    background_color: "#1A237E"
    theme_color: "#1A237E"